{
 "title": "Xiaomi Air Purifier 4 Lite Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Name",
    "label": "Room",
    "query": {
     "query": "label_values(mi_purifier_power,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mi_purifier_mode{name=\"$Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Manual Fan",
   "type": "stat",
   "description": "Manual Mode only, does not reflect on Auto/Sleep mode",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mi_purifier_favorite_level{name=\"$Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Fault",
   "type": "stat",
   "description": "0 - No Faults 无错误\n2 - Motor Stop 电机堵转\n3 - Sensor Lost 颗粒物传感器异常",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mi_purifier_fault{name=\"$Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AQI Level (PM2.5 concentration)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "mi_purifier_aqi{name=\"$Name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Filter Used Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mi_purifier_filter_used_time{name=\"Bedroom\"}",
     "legendFormat": "{{name}} Filter Days Used"
    }
   ]
  },
  {
   "title": "Remaining Filter Life",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mi_purifier_filter_life_remaining_percent{name=\"$Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Fan Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mi_purifier_fan_speed_rpm{name=\"$Name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filter Life",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "mi_purifier_filter_left_time{name=\"$Name\"}",
     "legendFormat": "{{name}} Filter Days Remaining"
    },
    {
     "expr": "mi_purifier_filter_used_time{name=\"$Name\"}",
     "legendFormat": "{{name}} Filter Days Used"
    }
   ]
  },
  {
   "title": "Temperature and Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "mi_purifier_humidity{name=\"$Name\"}",
     "legendFormat": "{{name}} Humidity"
    },
    {
     "expr": "mi_purifier_temp{name=\"$Name\"}",
     "legendFormat": "{{name}} Temperature"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "mi_purifier_power{name=\"$Name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}